apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-container2
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: k8s-container2
        image: us-east1-docker.pkg.dev/csci-5409-427620/k8s/container2:latest
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /Tanuj_PV_dir
          name: k8s-volume 
      volumes:
        - name: k8s-volume 
          persistentVolumeClaim:
            claimName: k8s-pvc
      
